### ISSUE TITLE
Dpmr mode does not work

### ISSUE THREAD

**Issue by landry76560** [moneriomaa/openear#51]
Hello admin

After testing Dpmr mode there is no voice setting or something to configure?

**Comment by moneriomaa** [comment]
Hello
which input is selected? Is it on an audio input device or rtl-usb or wav
file input?
Best Regards

**Comment by landry76560** [comment]
The input is on rtl-usb I tested with my transceiver but nothing works

Le lun. 31 août 2020 à 19:43, moneriomaa <notifications@github.com> a
écrit :

**Comment by moneriomaa** [comment]
i tested dpmr with some radios like kenwood and dPmr446 and it works
for more process can you record I/Q record by sdrsharp or raw audio input with dsd+ and send it to me for i check it?

**Comment by TheDefender44** [comment]
> 
> 
> Hello admin
> 
> After testing Dpmr mode there is no voice setting or something to configure?

I have to admit the sensitivity is a bit poor and weird on dPmr, but some voice comes out from my local conventional stations. Most of the time the sound is a little bit jerky, but I think it is because of my fairly old processor.

Have you tried to chirurgically position the IF tuning bar to get better audio ?

The problem I have is on NXDN48 trunked and conventional signals. It does not work either from wav. input nor from rtl-sdr input. No sound at all.

**Comment by moneriomaa** [comment]
> > Hello admin
> > After testing Dpmr mode there is no voice setting or something to configure?
> 
> I have to admit the sensitivity is a bit poor and weird on dPmr, but some voice comes out from my local conventional stations. Most of the time the sound is a little bit jerky, but I think it is because of my fairly old processor.
> 
> Have you tried to chirurgically position the IF tuning bar to get better audio ?
> 
> The problem I have is on NXDN48 trunked and conventional signals. It does not work either from wav. input nor from rtl-sdr input. No sound at all.

for more process can you record I/Q record by sdrsharp or raw audio input with dsd+ and send it to me for i check it?
you can send your files to moneriomaa@gmail.com

**Comment by landry76560** [comment]
Dsd + test with my Kirisun s780 transceiver in Dpmr mode frequency 446.0025
Mhz no voice
[image: Capture.JPG]

Le lun. 31 août 2020 à 21:39, moneriomaa <notifications@github.com> a
écrit :

**Comment by moneriomaa** [comment]
**_Dsd + test with my Kirisun s780 transceiver in Dpmr mode frequency 446.0025 Mhz no voice_**

the quality of output voice depends on correct center selection, dpmr is narrow signal and needs more accuracy on click
and it is hard without zoom, i think there is little issue on click in zoomed spectrum!
i try to find and solve it

for more process can you record I/Q record by sdrsharp or raw audio input with dsd+ and send it to me for i check it?
you can send your files to moneriomaa@gmail.com

**Comment by TheDefender44** [comment]
> 
> Dsd + test with my Kirisun s780 transceiver in Dpmr mode frequency 446.0025 Mhz no voice > […](#)

Hi Landry - dPmr on Openear has been tested with Kenwood dPmr samples. Some chinese radios claiming to be DPMR are also not DPMR compatible, like the Kirisun s780 transceiver. They are not using the standard dPmr protocol but their own proprietary protocol called "Kipro", hence the fact it didn't work with the Kenwood dPmr and Openear.

The word dPmr seems to be a generic term in china for a digital radio operating on 6.25khz, but does not necessarily mean in complies with the standard dPmr protocol.

I believe that's why dPmr does not work with your tests. Try some Kenwood it should work ok.

**Comment by landry76560** [comment]
Okay i understand better why thank you all for the info i will try to get a
kenwood

Le lun. 31 août 2020 à 22:27, TheDefender44 <notifications@github.com> a
écrit :
